version: '3.7'
services:
  app:
    image: orderdetails:LATEST
    restart: on-failure
    build:
      context: .
    ports:
      - 9080:9080
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/practice?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DATABASE_HOST: jdbc:mysql://docker-mysql:3306/practice?autoReconnect=true
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    expose:
      - "3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 5


volumes:

  sql:
networks:
  mynetwork:
    driver: bridge


